############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1
identifier = "home"

[[main]]
name = "About"
url = "about/"
weight = 2
identifier = "about"

# [[main]]
# name = "Authors"
# url = "authors/"
# weight = 2
# identifier = "authors"

[[main]]
name = "Rules"
url = "rules/"
weight = 3
identifier = "rules"

[[main]]
# parent = "Pages"
name = "Categories"
url = "categories/"
identifier = "pages"

[[main]]
# parent = "Pages"
name = "Tags"
url = "tags/"
identifier = "pages"

[[main]]
# parent = "Pages"
name = "Glossary"
url = "glossary/"
weight = 15
identifier = "glossary"